In [ ]:
a = 10
b = 50
print(a % b)

10

In [ ]:
a = 10
b = 50
print(a + b)

60

In [ ]:
a = 10
b = 50
print(a - b)
print(type(a))

-40
<class 'int'>

In [ ]:
a = 10
b = 50
print(a / b)

0.2

In [ ]:
a = 10
b = 50
print(a * b)

500

In [ ]:
name = input("Enter your name-->")
age = int(input("Enter your age -->"))
dept = input("enter your department-->")
num = int(input("Enter your phone no.-->"))
print(name)
print(f"I am {age} years old")
print(dept)
print(num)

Enter your name-->Devansh tiwari
Enter your age -->18
enter your department-->AIML
Enter your phone no.-->12341234
Devansh tiwari
I am 18 years old
AIML
12341234

In [ ]:
name = "DEVANSH TIWARI"
print(name.lower())
len(name)

devansh tiwari

14

In [ ]:
num = int(input("enter number -->"))
if num< 0:
  num = -num
if num /10 >=1:
  print("number is double digit")
else:
  print("number is single digit")

enter number -->-12
number is double digit

In [ ]:
for i in range(1,11):
  print(f"5 x {i} = {5*i}")

5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50

In [ ]:
a=int(input("enter first number-> "))
b=int(input("enter second number-> "))
op = input("enter operator(+,-,/,*)-> ")
if op == "+" :
  print(a+b)
elif op == "-":
  print(a-b)
elif op == "*":
  print(a*b)
elif op == "/":
  if b == 0:
    print("division error")
  else:
    print(a/b)
else:
  print("invalid input")

enter first number-> 23
enter second number-> 0
enter operator(+,-,/,*)-> /
division error

In [ ]:
name = "mom"
print(name[::-1])

mom

In [ ]:
num = input("Enter the number: ")
num1 = num
num2 = num1[::-1]
if num2 == num:
  print(f"the number {num} is palindrome")
else:
  print("not a palindrome")

Enter the number: 1221
the number 1221 is palindrome

In [ ]:
name = "harshit"
title = "Mr."
print(name+" "+ title)

harshit Mr.

In [ ]:
name = "                      ronaldo"
print(name.find("l"))
print(name.count(" "))

26
22

In [ ]:
a = [10,20,30]
b =[55,67]
a.append(90)
print(a)
print(a+b)
print(a[0])
print(a[0:2])
print(20 in a)

[10, 20, 30, 90]
[10, 20, 30, 90, 55, 67]
10
[10, 20]
True

In [ ]:
pip install notebook

Requirement already satisfied: notebook in /usr/local/lib/python3.12/dist-packages (6.5.7)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from notebook) (3.1.6)
Requirement already satisfied: tornado>=6.1 in /usr/local/lib/python3.12/dist-packages (from notebook) (6.5.7)
Requirement already satisfied: pyzmq>=17 in /usr/local/lib/python3.12/dist-packages (from notebook) (26.2.1)
Requirement already satisfied: argon2-cffi in /usr/local/lib/python3.12/dist-packages (from notebook) (25.1.0)
Requirement already satisfied: traitlets>=4.2.1 in /usr/local/lib/python3.12/dist-packages (from notebook) (5.7.1)
Requirement already satisfied: jupyter-core>=4.6.1 in /usr/local/lib/python3.12/dist-packages (from notebook) (5.9.1)
Requirement already satisfied: jupyter-client<8,>=5.3.4 in /usr/local/lib/python3.12/dist-packages (from notebook) (7.4.9)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.12/dist-packages (from notebook) (0.2.0)
Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (from notebook) (5.10.4)
Requirement already satisfied: nbconvert>=5 in /usr/local/lib/python3.12/dist-packages (from notebook) (7.17.1)
Requirement already satisfied: nest-asyncio>=1.5 in /usr/local/lib/python3.12/dist-packages (from notebook) (1.6.0)
Requirement already satisfied: ipykernel in /usr/local/lib/python3.12/dist-packages (from notebook) (6.17.1)
Requirement already satisfied: Send2Trash>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from notebook) (2.1.0)
Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.12/dist-packages (from notebook) (0.18.1)
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.12/dist-packages (from notebook) (0.25.0)
Requirement already satisfied: nbclassic>=0.4.7 in /usr/local/lib/python3.12/dist-packages (from notebook) (1.3.3)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from jupyter-client<8,>=5.3.4->notebook) (0.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from jupyter-client<8,>=5.3.4->notebook) (2.9.0.post0)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core>=4.6.1->notebook) (4.10.0)
Requirement already satisfied: notebook-shim>=0.2.3 in /usr/local/lib/python3.12/dist-packages (from nbclassic>=0.4.7->notebook) (0.2.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook) (4.13.5)
Requirement already satisfied: bleach!=5.0.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert>=5->notebook) (6.4.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook) (0.3.0)
Requirement already satisfied: markupsafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook) (3.0.3)
Requirement already satisfied: mistune<4,>=2.0.3 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook) (3.3.3)
Requirement already satisfied: nbclient>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook) (0.10.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook) (26.2)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook) (1.5.1)
Requirement already satisfied: pygments>=2.4.1 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook) (2.20.0)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat->notebook) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat->notebook) (4.26.0)
Requirement already satisfied: ptyprocess in /usr/local/lib/python3.12/dist-packages (from terminado>=0.8.3->notebook) (0.7.0)
Requirement already satisfied: argon2-cffi-bindings in /usr/local/lib/python3.12/dist-packages (from argon2-cffi->notebook) (25.1.0)
Requirement already satisfied: debugpy>=1.0 in /usr/local/lib/python3.12/dist-packages (from ipykernel->notebook) (1.8.15)
Requirement already satisfied: ipython>=7.23.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel->notebook) (7.34.0)
Requirement already satisfied: matplotlib-inline>=0.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel->notebook) (0.2.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from ipykernel->notebook) (5.9.5)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert>=5->notebook) (0.5.1)
Requirement already satisfied: tinycss2>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert>=5->notebook) (1.5.1)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->notebook) (75.2.0)
Collecting jedi>=0.16 (from ipython>=7.23.1->ipykernel->notebook)
  Downloading jedi-0.20.0-py2.py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->notebook) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->notebook) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->notebook) (3.0.52)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->notebook) (0.2.0)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->notebook) (4.9.0)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->notebook) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->notebook) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->notebook) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->notebook) (2026.6.3)
Requirement already satisfied: jupyter-server<3,>=1.8 in /usr/local/lib/python3.12/dist-packages (from notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook) (2.20.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->jupyter-client<8,>=5.3.4->notebook) (1.17.0)
Requirement already satisfied: cffi>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from argon2-cffi-bindings->argon2-cffi->notebook) (2.1.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->nbconvert>=5->notebook) (2.8.4)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->nbconvert>=5->notebook) (4.16.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->notebook) (3.0)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel->notebook) (0.8.7)
Requirement already satisfied: anyio>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook) (4.14.2)
Requirement already satisfied: jupyter-events>=0.11.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook) (0.12.1)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook) (0.5.4)
Requirement already satisfied: websocket-client>=1.7 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook) (1.9.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=7.23.1->ipykernel->notebook) (0.8.2)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio>=3.1.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook) (3.18)
Requirement already satisfied: python-json-logger>=2.0.4 in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook) (4.1.0)
Requirement already satisfied: pyyaml>=5.3 in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook) (6.0.3)
Requirement already satisfied: rfc3339-validator in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook) (0.1.1)
Requirement already satisfied: fqdn in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook) (1.5.1)
Requirement already satisfied: isoduration in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook) (3.1.1)
Requirement already satisfied: rfc3987-syntax>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook) (1.1.0)
Requirement already satisfied: uri-template in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook) (25.10.0)
Requirement already satisfied: lark>=1.2.2 in /usr/local/lib/python3.12/dist-packages (from rfc3987-syntax>=1.1.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook) (1.3.1)
Requirement already satisfied: arrow>=0.15.0 in /usr/local/lib/python3.12/dist-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook) (1.4.0)
Requirement already satisfied: tzdata in /usr/local/lib/python3.12/dist-packages (from arrow>=0.15.0->isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook) (2026.3)
Downloading jedi-0.20.0-py2.py3-none-any.whl (4.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 113.8 MB/s eta 0:00:00
Installing collected packages: jedi
Successfully installed jedi-0.20.0

In [ ]:
import pandas as pd
marks = pd.Series([80,90,100])
print(marks)

0     80
1     90
2    100
dtype: int64

In [ ]:
students = {
  "Name":["Rahul","Amit","Priya"],
  "Age":[20,21,23],
  "Marks":[80,90,70]
}
df = pd.DataFrame(students)
print(df)

    Name  Age  Marks
0  Rahul   20     80
1   Amit   21     90
2  Priya   23     70

In [ ]:
import pandas as pd
df = pd.read_csv('/content/Zomato-data-.csv')
df.shape

(148, 7)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148 entries, 0 to 147
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         148 non-null    object
 1   online_order                 148 non-null    object
 2   book_table                   148 non-null    object
 3   rate                         148 non-null    object
 4   votes                        148 non-null    int64
 5   approx_cost(for two people)  148 non-null    int64
 6   listed_in(type)              148 non-null    object
dtypes: int64(2), object(5)
memory usage: 8.2+ KB

In [ ]:
import pandas as pd

data = {
    "Emp_ID": [101,102,103,104,105,106,107,108,109,110],
    "Name": ["Aman","Neha","Rahul","Priya","Karan",
             "Simran","Mohit","Anjali","Vikas","Pooja"],
    "Age": [24,25,23,28,30,26,27,24,29,25],
    "Department": ["HR","IT","Sales","IT","HR",
                   "Finance","Sales","IT","Finance","HR"],
    "Salary": [35000,50000,45000,60000,38000,
               55000,47000,62000,58000,40000],
    "City": ["Delhi","Lucknow","Noida","Delhi","Jaipur",
             "Noida","Lucknow","Delhi","Jaipur","Delhi"]
}

df = pd.DataFrame(data)
print(df)

   Emp_ID    Name  Age Department  Salary     City
0     101    Aman   24         HR   35000    Delhi
1     102    Neha   25         IT   50000  Lucknow
2     103   Rahul   23      Sales   45000    Noida
3     104   Priya   28         IT   60000    Delhi
4     105   Karan   30         HR   38000   Jaipur
5     106  Simran   26    Finance   55000    Noida
6     107   Mohit   27      Sales   47000  Lucknow
7     108  Anjali   24         IT   62000    Delhi
8     109   Vikas   29    Finance   58000   Jaipur
9     110   Pooja   25         HR   40000    Delhi

In [ ]:
df["Salary"].sum()

np.int64(490000)

In [ ]:
df["Name"].count()

np.int64(10)

In [ ]:
df["Department"].unique()

array(['HR', 'IT', 'Sales', 'Finance'], dtype=object)

In [ ]:
df["Department"].nunique()

4

In [ ]:
df["Bonus"]=df["Salary"]*0.5
print(df)

   Emp_ID Emp_Name  Age Department  Salary     City    Bonus
0     101     Aman   24         HR   35000    Delhi  17500.0
1     102     Neha   25         IT   50000  Lucknow  25000.0
2     103    Rahul   23      Sales   45000    Noida  22500.0
3     104    Priya   28         IT   60000    Delhi  30000.0
4     105    Karan   30         HR   38000   Jaipur  19000.0
5     106   Simran   26    Finance   55000    Noida  27500.0
6     107    Mohit   27      Sales   47000  Lucknow  23500.0
7     108   Anjali   24         IT   62000    Delhi  31000.0
8     109    Vikas   29    Finance   58000   Jaipur  29000.0
9     110    Pooja   25         HR   40000    Delhi  20000.0

In [ ]:
df.rename(columns={"Name":"Emp_Name"}, inplace=True)
print(df)

   Emp_ID Emp_Name  Age Department  Salary     City
0     101     Aman   24         HR   35000    Delhi
1     102     Neha   25         IT   50000  Lucknow
2     103    Rahul   23      Sales   45000    Noida
3     104    Priya   28         IT   60000    Delhi
4     105    Karan   30         HR   38000   Jaipur
5     106   Simran   26    Finance   55000    Noida
6     107    Mohit   27      Sales   47000  Lucknow
7     108   Anjali   24         IT   62000    Delhi
8     109    Vikas   29    Finance   58000   Jaipur
9     110    Pooja   25         HR   40000    Delhi

In [ ]:
print(df)

   Emp_ID Emp_Name  Age Department  Salary     City
0     101     Aman   24         HR   35000    Delhi
1     102     Neha   25         IT   50000  Lucknow
2     103    Rahul   23      Sales   45000    Noida
3     104    Priya   28         IT   60000    Delhi
4     105    Karan   30         HR   38000   Jaipur
5     106   Simran   26    Finance   55000    Noida
6     107    Mohit   27      Sales   47000  Lucknow
7     108   Anjali   24         IT   62000    Delhi
8     109    Vikas   29    Finance   58000   Jaipur
9     110    Pooja   25         HR   40000    Delhi

In [ ]:
if 'Bonus' in df.columns:
    df.drop('Bonus', axis=1, inplace=True)
print(df)

   Emp_ID Emp_Name  Age Department  Salary     City
0     101     Aman   24         HR   35000    Delhi
1     102     Neha   25         IT   50000  Lucknow
2     103    Rahul   23      Sales   45000    Noida
3     104    Priya   28         IT   60000    Delhi
4     105    Karan   30         HR   38000   Jaipur
5     106   Simran   26    Finance   55000    Noida
6     107    Mohit   27      Sales   47000  Lucknow
7     108   Anjali   24         IT   62000    Delhi
8     109    Vikas   29    Finance   58000   Jaipur
9     110    Pooja   25         HR   40000    Delhi

In [ ]:
if 'city' in df.columns:
  df.drop("City",axis=1,inplace=True)
print(df)

   Emp_ID Emp_Name  Age Department  Salary
0     101     Aman   24         HR   35000
1     102     Neha   25         IT   50000
2     103    Rahul   23      Sales   45000
3     104    Priya   28         IT   60000
4     105    Karan   30         HR   38000
5     106   Simran   26    Finance   55000
6     107    Mohit   27      Sales   47000
7     108   Anjali   24         IT   62000
8     109    Vikas   29    Finance   58000
9     110    Pooja   25         HR   40000

In [ ]:
df.isnull()

   Emp_ID  Emp_Name    Age  Department  Salary
0   False     False  False       False   False
1   False     False  False       False   False
2   False     False  False       False   False
3   False     False  False       False   False
4   False     False  False       False   False
5   False     False  False       False   False
6   False     False  False       False   False
7   False     False  False       False   False
8   False     False  False       False   False
9   False     False  False       False   False

In [ ]:
df.isnull().sum()

Emp_ID        0
Emp_Name      0
Age           0
Department    0
Salary        0
dtype: int64

In [ ]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df["Emp_Name"].isnull()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
Name: Emp_Name, dtype: bool

In [ ]:
df["City"]="Delhi"
print(df)

   Emp_ID Emp_Name  Age Department  Salary   City
0     101     Aman   24         HR   35000  Delhi
1     102     Neha   25         IT   50000  Delhi
2     103    Rahul   23      Sales   45000  Delhi
3     104    Priya   28         IT   60000  Delhi
4     105    Karan   30         HR   38000  Delhi
5     106   Simran   26    Finance   55000  Delhi
6     107    Mohit   27      Sales   47000  Delhi
7     108   Anjali   24         IT   62000  Delhi
8     109    Vikas   29    Finance   58000  Delhi
9     110    Pooja   25         HR   40000  Delhi

In [ ]:
import pandas as pd

data = {
    "Student_ID": [101,102,103,104,105,106,107,108,109,110,
                   111,112,113,114,115,116,117,118,119,120],

    "Name": ["Aman","Neha","Rahul","Priya","Karan",
             "Simran","Mohit","Anjali","Vikas","Pooja",
             "Rohit","Sneha","Arjun","Riya","Deepak",
             "Muskan","Yash","Komal","Abhishek","Nisha"],

    "Gender": ["Male","Female","Male","Female","Male",
               "Female","Male","Female","Male","Female",
               "Male","Female","Male","Female","Male",
               "Female","Male","Female","Male","Female"],

    "Age": [20,21,19,22,20,21,20,19,22,20,
            21,20,23,19,22,20,21,22,20,19],

    "Department": ["CSE","IT","ECE","CSE","IT",
                   "CSE","ECE","IT","CSE","ECE",
                   "IT","CSE","ECE","IT","CSE",
                   "ECE","IT","CSE","ECE","IT"],

    "Semester": [4,4,2,6,4,6,2,4,8,6,
                 2,8,6,4,8,2,6,4,8,2],

    "Marks": [85,92,78,95,67,88,72,91,81,76,
              69,94,73,89,97,66,82,90,79,84],

    "Attendance": [92,95,85,97,78,90,82,98,88,84,
                   80,96,83,91,99,76,89,94,87,92],

    "CGPA": [8.5,9.2,7.8,9.5,6.9,
             8.8,7.2,9.1,8.1,7.6,
             7.0,9.4,7.4,8.9,9.8,
             6.8,8.2,9.0,7.9,8.4],

    "City": ["Delhi","Lucknow","Noida","Jaipur","Delhi",
             "Noida","Lucknow","Delhi","Jaipur","Delhi",
             "Noida","Lucknow","Delhi","Jaipur","Delhi",
             "Noida","Lucknow","Delhi","Jaipur","Delhi"]
}

df = pd.DataFrame(data)

print(df)

    Student_ID      Name  Gender  Age Department  Semester  Marks  Attendance  \
0          101      Aman    Male   20        CSE         4     85          92
1          102      Neha  Female   21         IT         4     92          95
2          103     Rahul    Male   19        ECE         2     78          85
3          104     Priya  Female   22        CSE         6     95          97
4          105     Karan    Male   20         IT         4     67          78
5          106    Simran  Female   21        CSE         6     88          90
6          107     Mohit    Male   20        ECE         2     72          82
7          108    Anjali  Female   19         IT         4     91          98
8          109     Vikas    Male   22        CSE         8     81          88
9          110     Pooja  Female   20        ECE         6     76          84
10         111     Rohit    Male   21         IT         2     69          80
11         112     Sneha  Female   20        CSE         8     94          96
12         113     Arjun    Male   23        ECE         6     73          83
13         114      Riya  Female   19         IT         4     89          91
14         115    Deepak    Male   22        CSE         8     97          99
15         116    Muskan  Female   20        ECE         2     66          76
16         117      Yash    Male   21         IT         6     82          89
17         118     Komal  Female   22        CSE         4     90          94
18         119  Abhishek    Male   20        ECE         8     79          87
19         120     Nisha  Female   19         IT         2     84          92

    CGPA     City
0    8.5    Delhi
1    9.2  Lucknow
2    7.8    Noida
3    9.5   Jaipur
4    6.9    Delhi
5    8.8    Noida
6    7.2  Lucknow
7    9.1    Delhi
8    8.1   Jaipur
9    7.6    Delhi
10   7.0    Noida
11   9.4  Lucknow
12   7.4    Delhi
13   8.9   Jaipur
14   9.8    Delhi
15   6.8    Noida
16   8.2  Lucknow
17   9.0    Delhi
18   7.9   Jaipur
19   8.4    Delhi